### PR TITLE
Implement encoding for newc format

### PR DESCRIPTION
**Pull request by sbuller**

### CODE REVIEW

**Comment by finnp** [comment]
Hey this looks great. Thank you for contributing 👍 

Could you add new tests for it and make sure the existing ones are passing?

**Comment by sbuller** [comment]
I'm tearing my hair out over it right now. So far I've discovered END_OF_CPIO needs a different length for the name than gets calculated. I've also discovered there's some sort of bug with the newc code, but haven't been able to trace it down. The tests are clearly needed.

**Comment by sbuller** [comment]
I'm having trouble figuring out where responsibility for null termination falls. The command line tool `cpio` seems to expect null termination, but cpio-fs doesn't seem to be doing null termination and I can't see any null termination logic in cpio-stream. Nevertheless odc just seems to magically work.

**Comment by sbuller** [comment]
Looks like a bug in odc. padEven is always appending a '\0'. This works because odc isn't supposed to use any padding.

**Comment by finnp** [comment]
Nice that you were able to figure it out 👍

**Comment by sbuller** [comment]
I think the only thing left, is that I added default parameter values to both newc.encode and odc.encode. They're useful to make END_OF_CPIO simple, but they duplicate functionality from Pack::entry. I'm unsure which direction to go with this. Leave them? Remove the duplicated functionality from Pack::entry? Remove the duplicated functionality from the encode functions and provide values for all parameters for END_OF_CPIO?

**Comment by finnp** [comment]
Wow tests are passing :) 
I'd suggest to remove all `|| 0`, because falsy values are going to be treated as 0 by `encodeHex` anyway. This is actually true for lines that I wrote before as well like `if (!header.size) header.size = 0`, so they could also be removed.

For the rest of the default values, they are often different in Pack::entry to the values in the encoders. I'll suggest to leave those in both places. If they are the same, then just have them in the .encode and not the .pack function.

Does that make sense to you?

**Comment by finnp** [comment]
Also I'm a bit curious: What's your motivation for working on this? Just for fun or do you need it for something else?

**Comment by sbuller** [comment]
I put the `|| 0`s in because I was getting some `NaN`s. I'm working on this because I want to generate initramfs files to use with [NodeOS](https://github.com/NodeOS/NodeOS).

**Comment by finnp** [comment]
Okay then `|| 0` makes sense. But I'd remove the `if(!x) x = 0` statements then, if they point to 0 as well.

**Comment by sbuller** [comment]
I think I'm happy with this. Assuming I haven't blown the tests because of ES6 again.

**Comment by finnp** [comment]
Great thanks a lot for the contribution! I published it as v1.3.0.

**Pull request merged**
