### PR TITLE
[fix] Don't stream strike data

### PR DESCRIPTION
**Pull request by piranna**
This fixes a minimal corner case where strike data would sometimes be send as part of the file content.

### CODE REVIEW

**Comment by finnp** [comment]
Thanks! Merged it. Also added you as a collaborator for this package as you seem to be doing the most work on this right now 😄

**Comment by piranna** [comment]
> Thanks! Merged it. Also added you as a collaborator for this package as you seem to be doing the most work on this right now

Cool! Thank you :-) Is it already published on npm, or do I have publish permissions there?

**Comment by finnp** [comment]
@piranna It looks like I forgot to publish it 😆  But you're a collaborator on npm as well, so feel free to publish a new version 🎉

**Comment by piranna** [comment]
Published as 1.4.0 :-) There was already a 1.3.0 version from last summer that was not available on the Github repo.

**Pull request merged**
